export const ADD_STAFFSS = "ADD_STAFFSS";

export const STAFFS_LOADING = "STAFFS_LOADING";
export const STAFFS_FAILED = "STAFFS_FAILED";
export const ADD_STAFFS = "ADD_STAFFS";

export const ADD_DEPARTMENTS = "ADD_DEPARTMENTS";
export const DEPARTMENTS_FAILED = "DEPARTMENTS_FAILED";
export const DEPARTMENTS_LOADING = "DEPARTMENTS_LOADING";


export const STAFFSSALARY_LOADING = "STAFFSSALARY_LOADING";
export const ADD_STAFFSSALARY = "ADD_STAFFSSALARY";
export const STAFFSSALARY_FAILED = "STAFFSSALARY_FAILED";


export const DELETE_STAFFSS = "DELETE_STAFFSS";
